name: odi
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numba=0.41.0
  - numpy=1.13.1
  - pandas=0.23.4
  - pyyaml=3.13
  - plotly=3.4.2
  - scipy=1.2.1
  - click=7.0
  - matplotlib=3.0.3
